services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d northwind"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  view-initializer:
    image: alpine:latest
    container_name: view_initializer
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./views:/views
      - ./scripts/init_northwind_views.sh:/scripts/init_northwind_views.sh
    networks:
      - postgres_network
    restart: "no"  # Change from "always" to "no"
    command: ["/bin/sh", "/scripts/init_northwind_views.sh", "--cron"]

  database-initializer:
      image: alpine:latest
      container_name: database_initializer
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - ./init-other-db-scripts:/init-other-db-scripts  # Contains itau.sql, trigger.sql, acid.sql
        - ./scripts/init_db.sh:/scripts/init_db.sh  # Single generic script
      networks:
        - postgres_network
      restart: "no"
      command: 
        - /bin/sh
        - -c
        - |
          /scripts/init_db.sh itau
          /scripts/init_db.sh trigger
          /scripts/init_db.sh acid
          /scripts/init_db.sh queryorder
          /scripts/init_db.sh index_db
          /scripts/init_db.sh partition_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network: